# Generated by Django 3.1.4 on 2021-01-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='http://img.crazys.info/files/i/2010.10.1/1285929248_3.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
